### ISSUE TITLE
Make all glyphs same width?

### ISSUE THREAD

**Issue by djrrb** [TypeNetwork/RobotoMono#13]
I believe these are the relevant issues that would justify making all glyphs the same width in the monospace, and setting the appropriate flags:

https://github.com/google/fonts/issues/225
https://github.com/google/fonts/issues/251

cc @moyogo @pichotta @m4rc1e

**Comment by pichotta** [comment]
Adjusted to monospace width in font.
/hyphen/f/uni00AD/Omicrontonos/Omegatonos/uni049E/uni049F/Dcroat/Eth/hbar/dcroat/uni20AB/tcaron/Epsilontonos/Etatonos/Iotatonos/Upsilontonos/dcaron/lcaron/ldot/exclamdbl/

**Comment by pichotta** [comment]
Changed glyphs with zero width to font monowidth value.
_NULL dotbelow gravecomb acutecomb tildecomb hook uni030F_

**Comment by pichotta** [comment]
@djrrb @moyogo 
Do you know if the set width value for /NULL should be 'zero' or the same as the 'monowidth' value? To satisfy requirements for PuTTY?  See above issue #225

**Comment by pichotta** [comment]
Decision in weekly meeting to delete the /NULL.
