### ISSUE TITLE
PANOSE for monospace

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/RobotoMono#16]
@moyogo 
https://github.com/google/fonts/issues/225

![PANOSE](https://user-images.githubusercontent.com/6576107/79690051-7b773700-8226-11ea-8a19-e045c27fde70.png)

**Comment by moyogo** [comment]
Fixed glyphs in 492c8c3 and with `gftools fix-isfixedpitch` in 75cd8afb and 8e54d6ce.
