### ISSUE TITLE
Italics are missing smcp glyphs

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/RobotoMono#18]
![glyphs_missing](https://user-images.githubusercontent.com/7525512/80218188-c3d49180-8638-11ea-9219-4f12f17669e7.gif)

**Comment by pichotta** [comment]
@moyogo 
The small caps are in the generated TTFs.
The show up in the VF  [wght].ttf in DinamoDarkroom

![RobotoMono SC 2020-04-24 at 9 53 10 AM](https://user-images.githubusercontent.com/6576107/80220430-d25b8280-8611-11ea-91a8-ded8d16467ff.png)

**Comment by pichotta** [comment]
@moyogo 

The Italic small caps are visible in the generated TTF

They are also visible in the variable RobotoMono-Italic[wght].ttf in DinamoDarkroom.

![Uploading RobotoMono-Italic[wght].ttf 2020-04-24 at 9.57.26 AM.png…]()

**Comment by m4rc1e** [comment]
> The Italic small caps are visible in the generated TTF

If I enable the smcp feature on the italic fonts, small caps are not shaped.

```
$ hb-shape RobotoMono-Italic\[wght\].ttf "a" --features="smcp"
[a=0+1202]
```

It works for Roman

```
$ hb-shape RobotoMono\[wght\].ttf "a" --features="smcp"
[A.smcp=0+1229]
```
