### ISSUE TITLE
WinAscent is lower than font yMax

### ISSUE THREAD

**Issue by moyogo** [TypeNetwork/RobotoMono#3]
The latest released Roboto Mono and the one build from sources trigger the following fontbakery fail.
I assume we don’t want to change Roboto Mono’s font metrics and should ignore this fail.
Can you confirm?

🔥 FAIL: Checking OS/2 usWinAscent & usWinDescent.
com.google.fonts/check/family/win_ascent_and_descent
--- Rationale ---

A font's winAscent and winDescent values should be greater than the head
table's yMax, abs(yMin) values. If they are less than these values, clipping
can occur on Windows platforms
(https://github.com/RedHatBrand/Overpass/issues/33).

If the font includes tall/deep writing systems such as Arabic or Devanagari,
the winAscent and winDescent can be greater than the yMax and abs(yMin) to
accommodate vowel marks.

When the win Metrics are significantly greater than the upm, the linespacing
can appear too loose. To counteract this, enabling the OS/2 fsSelection bit 7
(Use_Typo_Metrics), will force Windows to use the OS/2 typo values instead.
This means the font developer can control the linespacing with the typo values,
whilst avoiding clipping by setting the win values to values greater than the
yMax and abs(yMin).

🔥 FAIL OS/2.usWinAscent value should be equal or greater than 2163, but got 2146 instead [code: ascent]

**Comment by moyogo** [comment]
@m4rc1e

**Comment by pichotta** [comment]
@m4rc1e
closing this Issue re: Roboto Mono font metrics.  I believe we agreed verbally that the font metrics should remain the same.
